import Head from "next/head";
import Row from "../src/components/Row";
import { getProviders, getSession, useSession } from "next-auth/react";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>PrimeTime - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Row title="Trending Movies" route="/api/movie/trending" />
      <Row title="Trending Tv" route="/api/tv/trending" />
    </div>
  );
}
export const getServerSideProps = async (ctx) => {
  const session = await getSession(ctx);
  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
